baseURL = 'https://vanvj00002.github.io/monkvan/'
languageCode = 'zh-CN'
title = 'monkvan'
theme = ["fixit"]

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
mainSections = ["posts"]
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

[params]
  version = "0.3.X"
  since = 2025
  description = "老梵的个人随笔和思考"
  
  [params.author]
    name = "老梵"
  
  [params.home]
    sort = "date"
    paginate = 12
    dateFormat = "2006-01-02"
    readMore = true
    

  
  [params.page]
    hiddenFromHomePage = false
    enableToC = true
    enableLastmod = true
    
  [params.archives]
    dateFormat = "01-02"
    
  [params.search]
    enable = true
    type = "fuse"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "index"
    name = "索引"
    url = "/index/"
    weight = 3
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
